apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backend-deployment.yaml
  - backend-svc.yaml
  - zenoh-deployment.yaml
  - zenoh-svc.yaml
  - zenoh-configmap.yaml
  - ingressroute.yaml
