apiVersion: v1
kind: Service
metadata:
  name: zenoh-service
  namespace: nekazari
  labels:
    app: zenoh-router
    module: robotics
spec:
  selector:
    app: zenoh-router
  ports:
    - name: tcp
      port: 7447
      targetPort: 7447
      protocol: TCP
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
